- name: install bundler gem
  shell: bash -c "source /etc/profile.d/rvm.sh && gem install bundler"

- name: install cassandra-web gem
  shell: bash -c "source /etc/profile.d/rvm.sh && gem install cassandra-web"

- name: put a systemctl unit file
  template: src=cassandra-web.service dest=/etc/systemd/system/cassandra-web.service
  when: "(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>'))) or (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7')"

- name: enable and start cassandra-web service
  service: name="cassandra-web" enabled=yes state=started
  when: "(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>'))) or (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7')"
